package com.fluffybacon.merchantvillager.merchant;

public enum MerchantState {
    IDLE,
    SCANNING,
    SELECTING_TARGET,
    PLANNING_BATCH,
    RESERVING_INPUTS,
    COLLECTING_INPUTS,
    TRAVELLING_TO_TARGET,
    WAITING_FOR_TARGET,
    TRADING_BUSY,
    EXECUTING_TRADES,
    REVIEWING_REWARDS,
    RETURNING_TO_POST,
    RETURNING_UNUSED_INPUTS,
    FINDING_OUTPUT_CHEST,
    TRAVELLING_TO_OUTPUT_CHEST,
    DEPOSITING_REWARDS,
    WAITING_FOR_OUTPUT_SPACE,
    RECOVERING,
    PAUSED
}
